Auto Differentiation to perform BACK PROPOGATION

In [2]:
import torch 
import torch.nn as nn
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
print(x)
# w and b are parameters to be optimized so we specify by requires_grad
w = torch.randn(5, 3, requires_grad=True) 
print(w)
b = torch.randn(3, requires_grad=True)
print(b)
z = torch.matmul(x, w)+b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)

tensor([1., 1., 1., 1., 1.])
tensor([[ 0.1591, -0.8831,  0.6827],
        [ 1.7803, -0.6130, -0.3973],
        [ 1.1180, -0.1518,  0.5097],
        [-1.8461, -0.2909, -0.1512],
        [ 0.0472, -2.1963, -0.3511]], requires_grad=True)
tensor([1.7407, 0.0812, 0.4359], requires_grad=True)


In [3]:
# A reference to the backward propagation function is stored in grad_fn property of a tensor. 
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

Gradient function for z = <AddBackward0 object at 0x000001C10DD21600>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001C10DD0C910>


In [4]:
loss.backward() # calculate the 
print(w.grad) # new value of w 
print(b.grad)

tensor([[0.3175, 0.0057, 0.2248],
        [0.3175, 0.0057, 0.2248],
        [0.3175, 0.0057, 0.2248],
        [0.3175, 0.0057, 0.2248],
        [0.3175, 0.0057, 0.2248]])
tensor([0.3175, 0.0057, 0.2248])


We can only obtain the grad properties for the leaf nodes of the computational graph, which have requires_grad property set to True.

In [ ]:
""" To stop support for gradient computation. for example, when we have trained the model and just want to apply it to some input data,
 i.e. we only want to do forward computations through the network.
"""
with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

with torch.no_grad():
    z = torch.matmul(x, w)+b
print(z.requires_grad)

MAE

In [ ]:
loss = nn.L1Loss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

MSE

In [ ]:
loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
output = loss(input, target)
output.backward()

Creates a criterion that uses a squared term if the absolute element-wise error falls below delta and a delta-scaled L1 term otherwise

In [ ]:
loss = nn.HuberLoss()

CrossEntropyLoss criterion computes the cross entropy loss between input logits and target.

It is useful when training a classification problem with C classes.

In [ ]:
loss - nn.NLL() 
"""  
The negative log likelihood takes the argmax from the vector returned by softmax and takes negative log and we wnat that to be small
"""

In [ ]:
 #Example of target with class probabilities
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5).softmax(dim=1)
output = loss(input, target)
output.backward()
