In [2]:
%pwd

'/content'

In [3]:
%ls

sample_data/


In [4]:
%mkdir learningtensor

In [9]:
%cd


/root


In [10]:
%cd /content/learningtensor

/content/learningtensor


In [14]:
%pwd

'/content/learningtensor'

In [12]:
# For tips on running notebooks in Google Colab, see
# https://pytorch.org/tutorials/beginner/colab
%matplotlib inline

[Learn the Basics](intro.html) \|\|
[Quickstart](quickstart_tutorial.html) \|\| **Tensors** \|\| [Datasets &
DataLoaders](data_tutorial.html) \|\|
[Transforms](transforms_tutorial.html) \|\| [Build
Model](buildmodel_tutorial.html) \|\|
[Autograd](autogradqs_tutorial.html) \|\|
[Optimization](optimization_tutorial.html) \|\| [Save & Load
Model](saveloadrun_tutorial.html)

Tensors
=======

Tensors are a specialized data structure that are very similar to arrays
and matrices. In PyTorch, we use tensors to encode the inputs and
outputs of a model, as well as the model's parameters.

Tensors are similar to [NumPy's](https://numpy.org/) ndarrays, except
that tensors can run on GPUs or other hardware accelerators. In fact,
tensors and NumPy arrays can often share the same underlying memory,
eliminating the need to copy data (see
`bridge-to-np-label`{.interpreted-text role="ref"}). Tensors are also
optimized for automatic differentiation (we\'ll see more about that
later in the [Autograd](autogradqs_tutorial.html) section). If you're
familiar with ndarrays, you'll be right at home with the Tensor API. If
not, follow along!


In [2]:
import torch
import numpy as np

Initializing a Tensor
=====================

Tensors can be initialized in various ways. Take a look at the following
examples:

**Directly from data**

Tensors can be created directly from data. The data type is
automatically inferred.


In [16]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [18]:
mydata= [[1,2,3],[4,5,6],[7,8,9]]
mytensor=torch.tensor(mydata)
print(mytensor)
print(mytensor.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.int64


**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see
`bridge-to-np-label`{.interpreted-text role="ref"}).


In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [27]:
data2=(1,2,3,4,5,6)
npArray = np.array(data2)
tensordata=torch.tensor(data2)
print(npArray)
print(tensordata)

npArray2 = np.array(mydata)
print(npArray2)
tensordata2=torch.tensor(npArray2)
print(tensordata2)

npArray3= np.array([[1,2,3],[4,5,6],[7,8,9]])

tensordata3= torch.from_numpy(npArray3)
print(tensordata3)



[1 2 3 4 5 6]
tensor([1, 2, 3, 4, 5, 6])
[[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument
tensor, unless explicitly overridden.


In [43]:
print(x_data)
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")


tensor([[1, 2],
        [3, 4]])
Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8586, 0.7185],
        [0.0908, 0.6454]]) 



checking of shape of **tensor**

In [ ]:
print(x_rand.size())

In [38]:
random = torch.rand_like(tensordata2, dtype=torch.float)
print(random)

tensor([[0.2489, 0.5853, 0.6146],
        [0.9033, 0.7562, 0.0108],
        [0.9546, 0.6777, 0.0093]])


**With random or constant values:**

`shape` is a tuple of tensor dimensions. In the functions below, it
determines the dimensionality of the output tensor.


In [45]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print( rand_tensor)


print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

tensor([[0.1756, 0.4682, 0.0647],
        [0.0480, 0.9199, 0.3284]])
Random Tensor: 
 tensor([[0.1756, 0.4682, 0.0647],
        [0.0480, 0.9199, 0.3284]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


------------------------------------------------------------------------


Attributes of a Tensor
======================

Tensor attributes describe their shape, datatype, and the device on
which they are stored.


In [4]:
tensor = torch.rand(3,4)
print(tensor.size())
print(tensor.shape)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

torch.Size([3, 4])
torch.Size([3, 4])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


------------------------------------------------------------------------


Operations on Tensors
=====================

Over 100 tensor operations, including arithmetic, linear algebra, matrix
manipulation (transposing, indexing, slicing), sampling and more are
comprehensively described
[here](https://pytorch.org/docs/stable/torch.html).

Each of these operations can be run on the GPU (at typically higher
speeds than on a CPU). If you're using Colab, allocate a GPU by going to
Runtime \> Change runtime type \> GPU.

By default, tensors are created on the CPU. We need to explicitly move
tensors to the GPU using `.to` method (after checking for GPU
availability). Keep in mind that copying large tensors across devices
can be expensive in terms of time and memory!


In [5]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

# CUDA is NVIDIA's parallel computing architecture that enables dramatic increases in computing performance by harnessing the power of the GPU to speed up the most demanding tasks you run on your PC.

Try out some of the operations from the list. If you\'re familiar with
the NumPy API, you\'ll find the Tensor API a breeze to use.


**Standard numpy-like indexing and slicing:**


In [10]:
tensor = torch.rand(4, 4)
print(tensor)
print("First element", tensor[0][0])
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print("First column another way", tensor[...,0])
print(f"Last column: {tensor[:, -1]}")


tensor[:,1] = 0
print(tensor)

tensor([[0.1198, 0.2907, 0.9950, 0.4033],
        [0.3619, 0.1539, 0.8862, 0.8253],
        [0.7920, 0.5463, 0.3965, 0.6667],
        [0.1560, 0.0712, 0.3502, 0.7952]])
First element tensor(0.1198)
First row: tensor([0.1198, 0.2907, 0.9950, 0.4033])
First column: tensor([0.1198, 0.3619, 0.7920, 0.1560])
First column another way tensor([0.1198, 0.3619, 0.7920, 0.1560])
Last column: tensor([0.4033, 0.8253, 0.6667, 0.7952])
tensor([[0.1198, 0.0000, 0.9950, 0.4033],
        [0.3619, 0.0000, 0.8862, 0.8253],
        [0.7920, 0.0000, 0.3965, 0.6667],
        [0.1560, 0.0000, 0.3502, 0.7952]])


**Joining tensors** You can use `torch.cat` to concatenate a sequence of
tensors along a given dimension. See also
[torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html),
another tensor joining operator that is subtly different from
`torch.cat`.


In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[0.1198, 0.0000, 0.9950, 0.4033, 0.1198, 0.0000, 0.9950, 0.4033, 0.1198,
         0.0000, 0.9950, 0.4033],
        [0.3619, 0.0000, 0.8862, 0.8253, 0.3619, 0.0000, 0.8862, 0.8253, 0.3619,
         0.0000, 0.8862, 0.8253],
        [0.7920, 0.0000, 0.3965, 0.6667, 0.7920, 0.0000, 0.3965, 0.6667, 0.7920,
         0.0000, 0.3965, 0.6667],
        [0.1560, 0.0000, 0.3502, 0.7952, 0.1560, 0.0000, 0.3502, 0.7952, 0.1560,
         0.0000, 0.3502, 0.7952]])
torch.Size([4, 12])


**Arithmetic operations**


In [17]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T #python way of doing matric multiplication

y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) #stores result in y3


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.1198, 0.0000, 0.9950, 0.4033],
        [0.3619, 0.0000, 0.8862, 0.8253],
        [0.7920, 0.0000, 0.3965, 0.6667],
        [0.1560, 0.0000, 0.3502, 0.7952]])
tensor([[1.1670, 1.2580, 0.7583, 0.6879],
        [1.2580, 1.5974, 1.1882, 1.0231],
        [0.7583, 1.1882, 1.2289, 0.7925],
        [0.6879, 1.0231, 0.7925, 0.7793]])


tensor([[0.0144, 0.0000, 0.9901, 0.1626],
        [0.1310, 0.0000, 0.7854, 0.6811],
        [0.6272, 0.0000, 0.1572, 0.4444],
        [0.0243, 0.0000, 0.1227, 0.6323]])

**Single-element tensors** If you have a one-element tensor, for example
by aggregating all values of a tensor into one value, you can convert it
to a Python numerical value using `item()`:


In [20]:
print(tensor)
agg = tensor.sum()
print(agg)
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor([[0.1198, 0.0000, 0.9950, 0.4033],
        [0.3619, 0.0000, 0.8862, 0.8253],
        [0.7920, 0.0000, 0.3965, 0.6667],
        [0.1560, 0.0000, 0.3502, 0.7952]])
tensor(6.7481)
6.748071670532227 <class 'float'>


**In-place operations** Operations that store the result into the
operand are called in-place. They are denoted by a `_` suffix. For
example: `x.copy_(y)`, `x.t_()`, will change `x`.


In [23]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[5.1198, 5.0000, 5.9950, 5.4033],
        [5.3619, 5.0000, 5.8862, 5.8253],
        [5.7920, 5.0000, 5.3965, 5.6667],
        [5.1560, 5.0000, 5.3502, 5.7952]]) 

tensor([[10.1198, 10.0000, 10.9950, 10.4033],
        [10.3619, 10.0000, 10.8862, 10.8253],
        [10.7920, 10.0000, 10.3965, 10.6667],
        [10.1560, 10.0000, 10.3502, 10.7952]])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>
<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">
<p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate lossof history. Hence, their use is discouraged.</p>
</div>


------------------------------------------------------------------------


Bridge with NumPy {#bridge-to-np-label}
=================

Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change the other.


Tensor to NumPy array
=====================


In [24]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.


In [25]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy array to Tensor
=====================


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.


In [26]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([3., 3., 3., 3., 3.])
n: [3. 3. 3. 3. 3.]


## ***`Exercise One***

In [28]:
W= torch.rand(3,3)
print(W)

tensor([[0.4334, 0.4201, 0.6824],
        [0.2412, 0.6845, 0.3681],
        [0.1607, 0.6514, 0.4931]])


In [36]:
data = [[1.3],[2.6],[3.0]]
X = torch.tensor(data)
print(X)
print(X.shape)

tensor([[1.3000],
        [2.6000],
        [3.0000]])
torch.Size([3, 1])


In [32]:
B=torch.ones(3,1)
print(B)
print(B.shape)

tensor([[1.],
        [1.],
        [1.]])
torch.Size([3, 1])


In [78]:
Y = W.T @ X + B
print(Y)

tensor([[2.6727],
        [5.2799],
        [4.3234]])


In [ ]:
def dot_product_2d(matrix_a, matrix_b):
    # Ensure the inner dimensions match
    if len(matrix_a[0]) != len(matrix_b):
        raise ValueError("Inner dimensions must match for dot product")

    # Initialize the result matrix
    result = [[0 for _ in range(len(matrix_b[0]))] for _ in range(len(matrix_a))]

    # Perform the dot product
    for i in range(len(matrix_a)):
        for j in range(len(matrix_b[0])):
            for k in range(len(matrix_b)):
                result[i][j] += matrix_a[i][k] * matrix_b[k][j]

    return result

In [58]:
#checking min
minvalue=Y.min()
print(Y.min())
#checking max
maxvalue=Y.max()
print(maxvalue)
#checking standard devition
print(Y.std())

tensor(4.1974)
tensor(4.7028)
tensor(0.2558)


In [86]:
print(len(Y))
print(len(Y[0]))
# def checkingmax(Y):
#   for i in range(len(Y)):
#     for j in range(len(Y[i])):
#       if Y[i][j] == maxvalue:
#         index = [i][j]
#     return index
# print(checkingmax(Y))


3
1


In [79]:
# initialize weights or W with random numbers
Y

tensor([[2.6727],
        [5.2799],
        [4.3234]])

In [83]:
max_number = torch.argmax(Y).item()
max_number

1

# **Exercise 2**

# Implementing dot product by scratch
Pseudo Code:


In [95]:
Y = W.T @ X + B
print(Y)

tensor([[2.6727],
        [5.2799],
        [4.3234]])


In [98]:

# Transpose W
W_T = W.T




print(Y)

tensor([[2.6727],
        [5.2799],
        [4.3234]])


In [104]:
import time as t
start = t.time()
def functionforY(W_T,X,B):
    result = np.zeros((W_T.shape[0], X.shape[1]))
    if len(W_T[0]) != len(B):
        print("Wrong Dimensions")
    else:

        for i in range(W_T.shape[0]):
            for j in range(X.shape[1]):
                for k in range(W_T.shape[1]):
                    result[i][j] += W_T[i][k] * X[k][j]

        for i in range(result.shape[0]):
            for j in range(Y.shape[1]):
                result[i][j] += B[i][j]

    return Y

print(functionforY(W_T,X,B))
end = t.time()
print("for LOOPs:", end-start)
start2 = t.time()
Y = W.T @ X + B
print(Y)
end2 = t.time()
print("Direct ",end-start)




tensor([[2.6727],
        [5.2799],
        [4.3234]])
for LOOPs: 0.003556966781616211
tensor([[2.6727],
        [5.2799],
        [4.3234]])
Direct 0.003556966781616211
